### ISSUE TITLE
form with multiple buttons

### ISSUE THREAD

**Issue by Virgilio123** [palmtreephp/form#11]
I have created a form with the following code.

```
$builder = new FormBuilder([
    'key'             => 'Periodo',
    'method'          => 'POST',
    'html_validation' => false,
]);
	$builder
	->add('anno','choice',[
		'choices' => [
			'2022' => '2022',
			'2023' => '2023',
			'2024' => '2024'
		],
	])
	->add('mese','choice',[
		'choices' => [
			'01' => 'Gennaio',
			'02' => 'Febbraio',
			'03' => 'Marzo',
			'04' => 'Aprile',
			'05' => 'Maggio',
			'06' => 'Giugno',
			'07'=> 'Luglio',
			'08' => 'Agosto',
			'09' => 'Settembre',
			'10' => 'Ottobre',
			'11' => 'Novembre',
			'12' => 'Dicembre'
		],
	]);
 $builder->add('Salta','button');
$builder->add('Carica Calendario', 'submit');
$form = $builder->getForm();
```
**The HTML code related to the buttons is as follows:**
```
<div class="form-group mb-3">
        <button class="palmtree-form-control" type="button" id="form_Periodo-Salta" name="form_Periodo[Salta]" data-name="Salta">Salta</button>
</div>
<div class="form-group mb-3">
        <button class="btn btn-primary palmtree-form-control" type="submit" id="form_Periodo-Carica Calendario" name="form_Periodo[Carica Calendario]" value="" data-name="Carica Calendario">Carica Calendario</button>
</div>
```
Regarding this, it should be noted that the "Skip" button doesn't have any applied Bootstrap class, and I couldn't figure out how to associate a class like "btn btn-danger" and a command to the Click event.
Thank you very much for the excellent work.

**Comment by andyexeter** [comment]
The `ButtonType` doesn't have any classes by default:

https://github.com/palmtreephp/form/blob/0c2a1ca6c757add07f7c20f974affae5dd688839/src/Type/ButtonType.php#L17-L20

You can add your own like this:

```php
$builder->add('Salta','button', [
    'classes' => ['btn', 'btn-danger']
]);
```

However I am wondering whether to add `btn` and `btn-secondary` as the default classes for the ButtonType so they have some default styling at least.

**Comment by Virgilio123** [comment]
Thank you, I have tried it and it works correctly. But how do I associate a click event?

**Comment by andyexeter** [comment]
It'd be the same way you associate any other click event wouldn't it? e.g. https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#examples

**Comment by Virgilio123** [comment]
It would be better to directly insert a similar code into the HTML markup.

example:

`<button onclick="myFunction()">Click me</button>`
