### ISSUE TITLE
Data select (choices) with call database

### ISSUE THREAD

**Issue by SelMaK-fr** [palmtreephp/form#12]
Good morning,

This project is excellent, simple, light, a must. I integrated it into Slim Framework without much difficulty.

**I have a question** :

I have a list of items in the database (eg: item category), I would like to be able to retrieve it in a select (choices type) but I don't really know how to go about it. I thought about making a query directly in my Type class but I don't know if it's a good idea.
The second problem will arise with the data recorded in the database and make it “selected”.

Currently, I don't have an Entity yet but simply a Repository class which executes SQL queries.

How do I retrieve this list in a “Choices” field?

The example of one of my Type classes:

```
<?php
declare (strict_types = 1);
namespace App\Type;

use Palmtree\Form\FormBuilder;

class AccountType
{

    public function createFormBuilder(string|\stdClass|null|array $entity = null): FormBuilder
    {
        $builder = (new FormBuilder('account_form', $entity))
            ->add('fullname', 'text', [
                'error_message' => 'Please enter your fullname',
                'required' => true
            ])
            ->add('pseudo', 'text', [
                'required' => true
            ]);
        // SQL REQUEST IS HERE ? (I USE FLUENTPDO)
        $builder->add('role', 'choice', [
                'placeholder' => 'Select role',
                'choices'     => [
                    /** RESULT SQL REQUEST FOR ITEM CATEGORY */
                ],
            ])
            ;
        return $builder;
    }
}
```

Thank you very much for your work.

**Comment by andyexeter** [comment]
Hey there, thanks for the kind feedback.

I don't have much experience with Slim or FluentPDO but will try to help as best I can.

I understand you don't have an entity yet, but I presume your repository returns data as an array and that's what you are passing to the `createFormBuilder` method? You can bind arrays to the form, which I wrote a bit about here: https://github.com/palmtreephp/form/blob/d94af8572805fb77ad1ba47f1ca0200ee5cd7b00/docs/data-binding.md#array-data-mapping

Based on your sample code, I'd probably do something like this: 

```php
class AccountType
{

    public function createFormBuilder(string|\stdClass|null|array $entity = null): FormBuilder
    {
        $builder = (new FormBuilder('account_form', $entity))
            ->add('fullname', 'text', [
                'error_message' => 'Please enter your fullname',
                'required'      => true
            ])
            ->add('pseudo', 'text', [
                'required' => true
            ])
        ;

        $builder->add('role', 'choice', [
            'placeholder' => 'Select role',
            'choices'     => $this->getRoles(),
        ]);
        
        return $builder;
    }

    private function getRoles()
    {
        $roles = [];
        $query = $this->fluentPdo->from('roles');
        foreach ($query as $role) {
            $roles[$role['id']] = $role['name'];
        }

        return $roles;
    }
}
```

Then, assuming your `$entity` array looked something like this:

```
[
    'fullname' => 'SelMaK',
	'roles' => ['manager']
]
```

And assuming your roles database table has a `manager` role, this should be selected.

Hopefully this makes sense :smile: It might be helpful to take a look at the following test which uses an array for data binding:

https://github.com/palmtreephp/form/blob/0c2a1ca6c757add07f7c20f974affae5dd688839/tests/DataBindingTest.php#L57-L90

You could also take a look at the [data binding example](https://github.com/palmtreephp/form/blob/0c2a1ca6c757add07f7c20f974affae5dd688839/examples/data-binding/index.php)

**Comment by SelMaK-fr** [comment]
**It works flawlessly**. Thanks for your help. Your FormBuilder facilitates the development of my project.

Excellent work !
