### ISSUE TITLE
Define a value in a Text input

### ISSUE THREAD

**Issue by SelMaK-fr** [palmtreephp/form#17]
Hello,

I'm looking for a way to add a default TEXT type.
I tried to enter value like this:

```php
 ->add('users_id', 'text', [
     'value' => 'myValue'
 ])
```

But he doesn't take it.
So I wanted to create my own Type class but unfortunately, I'm stuck.
Following the source code, I am here : 

```php
use Palmtree\Form\Type\AbstractType;
use Palmtree\Html\Element;

class TextValueType extends AbstractType
{
    protected $type = 'text';

    protected string $value = 'dump';

    public function getElement(): Element
    {
        $element = parent::getElement();
        if ($this->value) {
            $element->attributes['value'] = $this->value;
        }

        return $element;
    }
}
```
If I give a value to my variable, ok, it works but how do I do it from the Builder?

Thanks :)

**Comment by andyexeter** [comment]
Hey @SelMaK-fr, there are a couple of ways to do this.

The simplest way is to set the `data` argument in the builder:

```php
 ->add('users_id', 'text', [
     'data' => 'myValue'
 ])
```

The more advanced way is to use [data binding](https://github.com/palmtreephp/form/blob/78f65e9841dc12169e7fea64049c13c118d1c6b1/docs/data-binding.md), like this:

```php
class Thing {
	public $users_id;
}

$thing = new Thing();
$thing->users_id = 'myValue';

$builder = new FormBuilder('some_form_key', $thing);

$builder->add('users_id', 'text')
// ...
```

**Comment by SelMaK-fr** [comment]
I'm really going to create DTOs in my project and use data binding, it will be simpler I think.

Thank you very much for your reply :)
