### ISSUE TITLE
Grid system support

### ISSUE THREAD

**Issue by ting7777** [palmtreephp/form#3]
i mean like following image, have row col-6 or col-3 like that
<img width="896" alt="Screenshot 2022-07-03 at 11 26 05 PM" src="https://user-images.githubusercontent.com/14001561/177118119-d0ed4975-f6b3-4862-8f5d-98fbc56273c3.png">

**Comment by luisgutie** [comment]
Any update on this?

**Comment by andyexeter** [comment]
@ting7777 @luisgutie I've created a pull request (#4) for this functionality - would be great if you could both take a look before I merge it in.

**Comment by andyexeter** [comment]
@ting7777 @luisgutie any feedback? 🙂

**Comment by ting7777** [comment]
@andyexeter sorry lately busy, tested work like a charm.

**Comment by andyexeter** [comment]
This has been merged and released as v4.3.0

**Comment by ting7777** [comment]
Hi andy,

why dont add this formdata? this will also able sent file as well.
[image: image.png]

**Comment by andyexeter** [comment]
@ting7777 I'm not really sure what you mean?

It looks like you meant to add an image to the comment but it didn't work.
